name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Linting and Code Quality
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run CSS linting
      run: npm run lint:css || true
    
    - name: Run JS linting
      run: npm run lint:js || true

  # PHP Code Standards
  phpcs:
    name: PHP Code Standards
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        tools: composer:v2
    
    - name: Install Composer dependencies
      run: composer install --no-progress --prefer-dist
    
    - name: Run PHP CodeSniffer
      run: composer run phpcs || true

  # Build and Package
  build:
    name: Build Theme
    runs-on: ubuntu-latest
    needs: [lint, phpcs]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build theme
      run: npm run build
    
    - name: Create theme package
      run: npm run create-zip
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: panolabo-theme
        path: panolabo-theme.zip
        retention-days: 30

  # Create Release (only on main branch)
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: panolabo-theme
    
    - name: Get version from style.css
      id: get_version
      run: |
        VERSION=$(grep "Version:" style.css | sed 's/.*Version: *//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        body: |
          ## 🚀 Panolabo Theme v${{ steps.get_version.outputs.version }}
          
          ### Changes
          - See commit history for details
          
          ### Installation
          1. Download `panolabo-theme.zip`
          2. Upload to WordPress admin panel
          3. Activate the theme
        draft: false
        prerelease: false
    
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./panolabo-theme.zip
        asset_name: panolabo-theme-v${{ steps.get_version.outputs.version }}.zip
        asset_content_type: application/zip